In [1]:
from sklearn.datasets import load_breast_cancer

In [3]:
dataset = load_breast_cancer()

In [4]:
X = dataset.data

In [5]:
X.shape

(569, 30)

In [7]:
X[1]

array([2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
       8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
       3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
       1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
       1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02])

In [9]:
y = dataset.target

In [12]:
y.shape

(569,)

In [13]:
from sklearn.model_selection import train_test_split

In [28]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size = 0.25, random_state = 42)

In [29]:
from sklearn.naive_bayes import GaussianNB

In [30]:
gnb = GaussianNB()

In [31]:
gnb

GaussianNB()

In [32]:
gnb.fit(xtrain,ytrain)

GaussianNB()

In [36]:
prediction  = gnb.predict(xtest)

In [37]:
prediction

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [39]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [41]:
accuracy_score(ytest,prediction)

0.958041958041958

In [42]:
confusion_matrix(ytest,prediction)

array([[51,  3],
       [ 3, 86]], dtype=int64)

In [43]:
from sklearn.datasets import fetch_20newsgroups

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
from sklearn.naive_bayes import BernoulliNB,MultinomialNB

In [75]:
newsgroups = fetch_20newsgroups(subset= 'all')

In [76]:
newsgroups.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [78]:
newsgroups.target

array([10,  3, 17, ...,  3,  1,  7])

In [110]:
vectorizer1 = CountVectorizer(binary = True)
vectorizer2 = CountVectorizer(binary = False)

In [121]:
X1 = vectorizer1.fit_transform(newsgroups.data)
X2 = vectorizer1.fit_transform(newsgroups.data)

In [122]:
newsgroups.data[0],newsgroups.target[0]

("From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>\nSubject: Pens fans reactions\nOrganization: Post Office, Carnegie Mellon, Pittsburgh, PA\nLines: 12\nNNTP-Posting-Host: po4.andrew.cmu.edu\n\n\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n",
 10)

In [123]:
X1[0]

<1x173762 sparse matrix of type '<class 'numpy.int64'>'
	with 110 stored elements in Compressed Sparse Row format>

In [124]:
X2[0]

<1x173762 sparse matrix of type '<class 'numpy.int64'>'
	with 110 stored elements in Compressed Sparse Row format>

In [125]:
y = newsgroups.target

In [126]:
y

array([10,  3, 17, ...,  3,  1,  7])

In [127]:
from sklearn.model_selection import train_test_split
xtrain1,xtest1,ytrain,ytest = train_test_split(X1,y,test_size = 0.25,random_state = 42)

In [128]:
xtrain2,xtest2,ytrain,ytest = train_test_split(X2,y,test_size = 0.25, random_state = 42)

In [129]:
bnb = BernoulliNB()
mnb = MultinomialNB()

In [130]:
bnb.fit(xtrain1,ytrain)

BernoulliNB()

In [131]:
mnb.fit(xtrain2,ytrain)

MultinomialNB()

In [139]:
y_pred1 = bnb.predict(xtest1)

In [140]:
y_pred2 = mnb.predict(xtest2)

In [141]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [142]:
accuracy_score(ytest,y_pred1)

0.6878183361629882

In [143]:
accuracy_score(ytest,y_pred2)

0.8569609507640068

In [146]:
confusion_matrix(ytest,y_pred1)

array([[ 81,   0,   0,   8,   0,   0,   6,   4,  51,   2,   1,   1,   1,
          2,   2,  36,   1,   2,   0,   0],
       [  0, 165,   0,  20,   0,   1,  48,   1,   3,   0,   0,   5,   1,
          0,   1,   0,   0,   0,   0,   0],
       [  0,  24,  22, 147,   3,   5,  26,   1,   4,   0,   0,   4,   5,
          0,   0,   0,   0,   0,   1,   0],
       [  0,   2,   0, 200,   1,   0,  30,   0,   0,   0,   0,   1,   4,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   1,  21, 187,   0,  37,   0,   1,   0,   0,   0,   1,
          0,   1,   0,   0,   0,   0,   0],
       [  0,  26,   0,  26,   2, 162,  39,   0,   4,   0,   0,   0,   1,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  20,   0,   0, 207,   3,   3,   0,   0,   0,   7,
          0,   1,   0,   0,   0,   0,   0],
       [  0,   1,   0,   3,   1,   0,  27, 204,   7,   0,   0,   1,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  10,   1, 208,   0,   0,  

In [147]:
confusion_matrix(ytest,y_pred2)

array([[173,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   2,  18,   0,   4,   1,   0],
       [  0, 207,   0,  13,   0,   2,   0,   1,   0,   0,   0,  11,   0,
          2,   3,   4,   0,   2,   0,   0],
       [  0,  25, 115,  65,   3,  12,   0,   2,   0,   0,   0,  16,   2,
          0,   0,   0,   2,   0,   0,   0],
       [  0,   9,   0, 209,   5,   1,   0,   1,   0,   0,   1,   5,   4,
          1,   1,   0,   1,   0,   0,   0],
       [  0,   3,   1,  15, 215,   1,   1,   0,   1,   0,   2,   3,   4,
          2,   1,   1,   0,   0,   0,   0],
       [  1,  23,   0,   8,   1, 216,   0,   0,   2,   1,   0,   4,   0,
          0,   2,   1,   1,   0,   0,   0],
       [  0,   3,   0,  31,   2,   0, 158,  13,   2,   0,   2,   5,  10,
          2,   4,   1,   4,   4,   0,   0],
       [  0,   2,   0,   1,   1,   0,   3, 228,   1,   0,   0,   2,   2,
          1,   0,   0,   2,   1,   0,   0],
       [  0,   0,   0,   1,   0,   0,   4,   7, 205,   0,   0,  